### ISSUE TITLE
Empty queue while get from feed queue

### ISSUE THREAD

**Issue by Vimos** [Yu-Wu/Decoupled-Novel-Object-Captioner#2]
I am getting the following exception while reading data, I guess the getting occurred before putting finishing.  
```
Traceback (most recent call last):
  File "/home/vimos/git/multimodal/DNOC/run.py", line 148, in <module>
    tf.compat.v1.app.run()
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/vimos/git/multimodal/DNOC/run.py", line 142, in main
    train()
  File "/home/vimos/git/multimodal/DNOC/run.py", line 80, in train
    batch = data_loader.next()
  File "/home/vimos/git/multimodal/DNOC/utils/dataloader.py", line 101, in next
    batch = self._feed_queue.get(timeout=10)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty
```

**Comment by Yu-Wu** [comment]
@Vimos 

Hi, could you please provide more details about this error?
It seems you also changed my code. So it is hard to localize the error.

**Comment by Vimos** [comment]
I am migrating the code to new TF version, most code are untouched.

The main difference is `tf.placeholder` --> `tf.compat.v1.placeholder`.

I can also offer a diff file but I am sure you will never want to read.

<details>

```
diff --git a/model.py b/model.py
index baf6dd2..6e37943 100755
--- a/model.py
+++ b/model.py
@@ -39,18 +39,18 @@ class DNOC(NNModel):
         self.dec_cell = self._get_dec_cell(self._dec_cell_size)
 
         # Inputs
-        self._enc_inputs = tf.placeholder(
+        self._enc_inputs = tf.compat.v1.placeholder(
             tf.float32,
             shape=[None, self._cnn_fea_dim],
             name="encode")
 
         for i in range(self._dec_seq_len):
-            self._dec_inputs.append(tf.placeholder(tf.int32, shape=[None], name="decoder{0}".format(i)))
-            self.target_weights.append(tf.placeholder(tf.float32, shape=[None], name="weight{0}".format(i)))
+            self._dec_inputs.append(tf.compat.v1.placeholder(tf.int32, shape=[None], name="decoder{0}".format(i)))
+            self.target_weights.append(tf.compat.v1.placeholder(tf.float32, shape=[None], name="weight{0}".format(i)))
 
-        self._det_feature = tf.placeholder(tf.float32, shape=[self._batch_size, FLAGS.max_det_boxes, FLAGS.det_fea_dim],
+        self._det_feature = tf.compat.v1.placeholder(tf.float32, shape=[self._batch_size, FLAGS.max_det_boxes, FLAGS.det_fea_dim],
                                            name="det_feature")
-        self._det_value = tf.placeholder(tf.int32, [self._batch_size, FLAGS.max_det_boxes], name="det_value")
+        self._det_value = tf.compat.v1.placeholder(tf.int32, [self._batch_size, FLAGS.max_det_boxes], name="det_value")
 
         # Targets
         targets = [self._dec_inputs[i + 1]
@@ -59,14 +59,14 @@ class DNOC(NNModel):
         self._query_targets = []  # the query target ground truth
         self._query_target_weights = []  # defines wthether the query loss is calculated at this pos
         for i in range(self._dec_seq_len):
-            self._query_targets.append(tf.placeholder(tf.int32, shape=[None], name="query_target{0}".format(i)))
+            self._query_targets.append(tf.compat.v1.placeholder(tf.int32, shape=[None], name="query_target{0}".format(i)))
             self._query_target_weights.append(
-                tf.placeholder(tf.float32, shape=[None], name="query_target_weight{0}".format(i)))
+                tf.compat.v1.placeholder(tf.float32, shape=[None], name="query_target_weight{0}".format(i)))
 
         # Encoder.
         image_feature = self._enc_inputs
         if self._phase_train:
-            image_feature = tf.nn.dropout(image_feature, keep_prob=0.5)
+            image_feature = tf.nn.dropout(image_feature, rate=0.5)
         image_feature = tf.contrib.layers.fully_connected(image_feature, FLAGS.dec_cell_size * 2, activation_fn=None,
                                                           scope="image_feature")
         self._enc_state = image_feature  # image feature
@@ -105,22 +105,22 @@ class DNOC(NNModel):
             query_value = tf.one_hot(self._det_value, FLAGS.detection_classes)
             return query_feature, query_value
 
-        # key value attention 
+        # key value attention
         def key_value_att(att_query, att_key, att_value):
-            with tf.variable_scope("Attention"):
+            with tf.compat.v1.variable_scope("Attention"):
                 weights = tf.matmul(att_key, att_query)
                 weights = tf.transpose(weights, perm=[0, 2, 1])
                 att_result = tf.matmul(weights, att_value)
                 att_result = tf.reshape(att_result, [att_result.shape[0], att_result.shape[2]])
             return att_result
 
-        with tf.variable_scope("generate_query_word", reuse=False):
+        with tf.compat.v1.variable_scope("generate_query_word", reuse=False):
             query_outputs = []
             for i, hstate in enumerate(hidden_states):
                 if i > 0:
-                    tf.get_variable_scope().reuse_variables()
+                    tf.compat.v1.get_variable_scope().reuse_variables()
 
-                # gen attation query, feature, value 
+                # gen attation query, feature, value
                 att_query = tf.split(hstate, 2, 1)[1]  # choose hidden states as the query
                 att_query = tf.expand_dims(att_query, 2)
 
@@ -131,7 +131,7 @@ class DNOC(NNModel):
                     att_query = tf.nn.dropout(att_query, keep_prob=0.5)
                     att_key = tf.nn.dropout(att_key, keep_prob=0.5)
 
-                    # query the memory and output the novel words logits
+                # query the memory and output the novel words logits
                 query_predict = key_value_att(att_query=att_query, att_key=att_key, att_value=att_value)
                 query_outputs.append(query_predict)
         return query_outputs
@@ -194,13 +194,13 @@ class DNOC(NNModel):
 
         # We define the last class of LSTM words to be <PL>.
         # Therefore, if the lstm output prediction equals "self.num_lstm_vocabs",
-        # we should take the word from query results to feed in the <PL>. 
+        # we should take the word from query results to feed in the <PL>.
         query_outputs[lstm_outputs != self.num_lstm_vocabs] = 0
 
         # In generating the held-out coco dataset, we reorganzied the vocab sequence,
         # so that detection words are at the last 80 places in the idx-to-word list.
         # For those need to be replaced, the lstm_output is self.num_lstm_vocabs,
-        # the query_outputs (in [0, 80]) is the indexs of detection words. 
+        # the query_outputs (in [0, 80]) is the indexs of detection words.
         # Therefore, lstm_outputs + query_outputs is the index for the final output.
         final_outputs = lstm_outputs + query_outputs
 
diff --git a/run.py b/run.py
index 84ff34a..c90e54a 100755
--- a/run.py
+++ b/run.py
@@ -1,4 +1,5 @@
 import os
+import time
 
 import tensorflow as tf
 
@@ -40,7 +41,7 @@ tf.app.flags.DEFINE_float('moving_average_decay', 0.999,
                           """moving_average_decay""")
 tf.app.flags.DEFINE_integer('max_gradient_norm', 5,
                             """max gradient norm""")
-# Captioning word setting 
+# Captioning word setting
 tf.app.flags.DEFINE_integer('PAD_ID', 0, "PAD")
 tf.app.flags.DEFINE_integer('GO_ID', 1, "GO")
 tf.app.flags.DEFINE_integer('EOS_ID', 2, "EOS")
@@ -52,12 +53,12 @@ tf.app.flags.DEFINE_integer('max_det_boxes', 4, "max_det_boxes")
 tf.app.flags.DEFINE_integer('det_fea_dim', 1088, "det_fea_dim")  # the detection feature is extracted by "prepare_data"
 
 FLAGS = tf.app.flags.FLAGS
-sess_config = tf.ConfigProto();
+sess_config = tf.compat.v1.ConfigProto()
 sess_config.gpu_options.allow_growth = True
 
 
 def train():
-    coord = tf.train.Coordinator()
+    coord = tf.compat.v1.train.Coordinator()
     data_loader = VisualTextData(coord)
     data_loader.start()
 
@@ -70,9 +71,10 @@ def train():
 
     # build model
     model = DNOC(num_total_vocab, num_lstm_vocabs)
-    with tf.Session(config=sess_config) as sess:
-        sess.run(tf.initialize_all_variables())
-        saver = tf.train.Saver(tf.all_variables(), max_to_keep=FLAGS.max_epochs)
+    with tf.compat.v1.Session(config=sess_config) as sess:
+        sess.run(tf.compat.v1.global_variables_initializer())
+        sess.run(tf.compat.v1.local_variables_initializer())
+        saver = tf.compat.v1.train.Saver(tf.compat.v1.global_variables(), max_to_keep=FLAGS.max_epochs)
 
         idx = 0
         while True:
@@ -144,4 +146,4 @@ def main(unused_argv):
 
 
 if __name__ == '__main__':
-    tf.app.run()
+    tf.compat.v1.app.run()
diff --git a/utils/captioning_metrics.py b/utils/captioning_metrics.py
index 8904e4b..526ba2a 100644
--- a/utils/captioning_metrics.py
+++ b/utils/captioning_metrics.py
@@ -1,13 +1,16 @@
 import sys
-
 import tensorflow as tf
 
 FLAGS = tf.app.flags.FLAGS
 LIBRARY_PATH = "./utils/coco-caption"
 sys.path.append(LIBRARY_PATH)
 
+from pycocoevalcap.bleu.bleu import Bleu
+from pycocoevalcap.rouge.rouge import Rouge
+from pycocoevalcap.cider.cider import Cider
 from pycocoevalcap.meteor.meteor import Meteor
 from pycocoevalcap.tokenizer.ptbtokenizer import PTBTokenizer
+import pickle as pkl
 import re
 
 # novel objects defined for MSCOCO
diff --git a/utils/models_base.py b/utils/models_base.py
index 2f62e56..68a2908 100755
--- a/utils/models_base.py
+++ b/utils/models_base.py
@@ -10,7 +10,7 @@ FLAGS = tf.app.flags.FLAGS
 
 class NNModel(object):
     def __init__(self):
-        self._global_step = tf.get_variable(
+        self._global_step = tf.compat.v1.get_variable(
             'global_step', [],
             initializer=tf.constant_initializer(0), trainable=False)
         self._total_loss = None
@@ -18,17 +18,17 @@ class NNModel(object):
         self._clip_gradients = FLAGS.max_gradient_norm
 
     def _get_train_op(self, clip_norm='', scope=None):
-        opt = tf.train.AdamOptimizer(FLAGS.lr)
+        opt = tf.compat.v1.train.AdamOptimizer(FLAGS.lr)
         regular_collection = ops.get_collection(ops.GraphKeys.REGULARIZATION_LOSSES, scope)
         total_loss = self._total_loss
 
         # Get Training Op
         variable_averages = tf.train.ExponentialMovingAverage(
             FLAGS.moving_average_decay, self._global_step)
-        variables_to_average = (tf.trainable_variables() +
-                                tf.moving_average_variables())
+        variables_to_average = (tf.compat.v1.trainable_variables() +
+                                tf.compat.v1.moving_average_variables())
         variables_averages_op = variable_averages.apply(variables_to_average)
-        batchnorm_updates = set(tf.get_collection(self._UPDATE_OPS_COLLECTION,
+        batchnorm_updates = set(tf.compat.v1.get_collection(self._UPDATE_OPS_COLLECTION,
                                                   scope))
         if batchnorm_updates:
             with tf.control_dependencies(batchnorm_updates):
@@ -43,21 +43,21 @@ class NNModel(object):
             self._global_norm = tf.global_norm(grads)
             gradients = _clip_gradients_by_norm(gradients, self._clip_gradients)
         else:
-            params = tf.trainable_variables()
+            params = tf.compat.v1.trainable_variables()
             gradients = tf.gradients(total_loss, params)
-            self._global_norm = tf.global_norm(gradients)
+            self._global_norm = tf.compat.v1.global_norm(gradients)
             if clip_norm == 'global':
                 gradients, _ = tf.clip_by_global_norm(gradients, self._clip_gradients)
             gradients = zip(gradients, params)
 
         apply_gradient_op = opt.apply_gradients(gradients, self._global_step)
         self._train_op = tf.group(apply_gradient_op, variables_averages_op)
-        summaries = tf.get_collection(tf.GraphKeys.SUMMARIES, scope)
-        for var in tf.trainable_variables():
-            summaries.append(tf.summary.histogram(
+        summaries = tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.SUMMARIES, scope)
+        for var in tf.compat.v1.trainable_variables():
+            summaries.append(tf.compat.v1.summary.histogram(
                 var.op.name, var))
         for grad, var in gradients:
             if grad is not None:
                 summaries.append(
-                    tf.summary.histogram(var.op.name + '/gradients', grad))
-        self._summary_op = tf.summary.merge(summaries)
+                    tf.compat.v1.summary.histogram(var.op.name + '/gradients', grad))
+        self._summary_op = tf.compat.v1.summary.merge(summaries)
```

</details>

**Comment by Yu-Wu** [comment]
@Vimos 

You are right.... I do not want to read the diff.

So, have you tested the code under older TF version, such as tf 1.10? 
It seems like the issue was raised by the data loader. It may lack some data in your environment.

I will carefully review this issue later.

**Comment by Vimos** [comment]
To tell you the truth, I once even succeeded in running on TF 1.14. 
However, the pipe is not guaranteed to be initialized with data. In most cases, it reports an `Empty Queue`.

**Comment by Yu-Wu** [comment]
Thanks for the report. 

It never shows an Empty Queue error in my environment. I am checking the code now.

**Comment by Yu-Wu** [comment]
@Vimos 

Sorry that I cannot reproduce the issue. I checked the code and found there might be two reasons:

1. Some running error in  the function https://github.com/Yu-Wu/Decoupled-Novel-Object-Captioner/blob/0565529ffc9d5f23fca25782d88774046a828b75/data.py#L44.

For this case, there will be some error log shown on the screen ( if you do not add some try-except operation.)

Could you provide more details? Could you please paste the whole log that shows on the screen?


2. Due to some reason, the code could not finish the filling operation in the given time (10 seconds).
Could you please try to set the timeout to a little longer, such as 
```batch = self._feed_queue.get(timeout=50)```.

**Comment by Vimos** [comment]
Thanks for the detailed reply! I will give it a try.

**Comment by Vimos** [comment]
Your suggestion 2 works! Strange problem.

**Comment by Yu-Wu** [comment]
@Vimos 

Well... Is your device in a heavy load before running the code? Or maybe the disk speed limits the data preprocess.

**Comment by Vimos** [comment]
OK, I will close the issue then. Thanks for the help!
