### ISSUE TITLE
python run.py --stage train

### ISSUE THREAD

**Issue by NaehaSharif** [Yu-Wu/Decoupled-Novel-Object-Captioner#3]
Hi,
I am using Tensorflow 1.14 with python 3.6, on windows 10. I managed to complete all the steps of preparing data after some path modifications (windows....), however I am having problems with run.py while training. It is related to multiprocessing and Pickling, but I am unable to figure out exactly what.

Here are all the warnings and errors, can you please have a look.

`(py36tf) E:\Decoupled-Novel-Object-Captioner-master>python run.py --stage train
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From run.py:56: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From run.py:148: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "run.py", line 148, in <module>
    tf.app.run()
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run.py", line 142, in main
    train()
  File "run.py", line 63, in train
    data_loader.start()
  File "E:\Decoupled-Novel-Object-Captioner-master\utils\dataloader.py", line 48, in start
    t.start()
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

(py36tf) E:\Decoupled-Novel-Object-Captioner-master>C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From E:\Decoupled-Novel-Object-Captioner-master\run.py:56: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\22161668\AppData\Local\Continuum\anaconda3\envs\py36tf\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

**Comment by Yu-Wu** [comment]
@NaehaSharif 

Hi, Thanks for your interests on our DNOC paper. 
From the provided logs, I found it might blame the Pickle module (https://stackoverflow.com/questions/44144584/typeerror-cant-pickle-thread-lock-objects)

**Comment by Yu-Wu** [comment]
@NaehaSharif 

Please give me some time to solve this issue. It seems it only happens on Windows.

**Comment by NaehaSharif** [comment]
Thanks for getting back to me quickly. I will dig around as well and if i find a solution, I will update you.

**Comment by Yu-Wu** [comment]
@NaehaSharif 

I tried a lot, but I could not reproduce the error.

In addition, I checked my code and found that I never use ''Pickle'' in reading data. It seems the issue is due to the multiprocess on Windows.

First of all , please check all the pre-processed data files. If there is an empty file, it might raise the issue.

From my point of view, you may try two things to debug the issue:
1. Please try the multiprocessing module via a simple example code. It might be incorrect.
2. Rewriting the code in ``dataloader.py'' to a version without the Multiprocessing module.
